### ISSUE TITLE
What happened to `rawquery()`?

### ISSUE THREAD

**Issue by keltia** [open-aviation/pyopensky#22]
I was using 1.4, building my own query with:
```rust
    let ctx: Context = python! {
        from pyopensky.open import OpenskyImpalaWrapper

        opensky = OpenskyImpalaWrapper()

        print("From: ", 'start, "To: ", 'end, "BB=", 'bb)
        print("Segments: ", len('v1))
    };
// ...
            ctx.run(python! {
                seg = 'tm
                bb = 'bb
                q = "SELECT * FROM state_vectors_data4 \
                WHERE lat >= {} AND lat <= {} AND lon >= {} AND lon <= {} AND hour={}{};\
                ".format(bb[1], bb[3], bb[0], bb[2], seg, 'icao)

                df = opensky.rawdata(q)
                if df is None:
                    data = ""
                else:
                    data = df.to_csv()
            });
```
and wrapping all of these with the Rust `inline_python` crate.

(cf. https://github.com/keltia/fetiche-rs/blob/main/opensky-history/src/main.rs)

What happened to the `rawquery()` method?  Is the old API completely gone?

**Comment by xoolive** [comment]
Hi @keltia 

Yes we did a major refactoring in order to have a consistent api for both impala and trino. 

For your query, it would be documented here https://open-aviation.github.io/pyopensky/impala.html#pyopensky.impala.Impala.history

Create an impala object first with

from pyopensky.impala import Impala
impala = Impala()

Then 

impala.history() with the bounds attribute 

If you don't want to change anything, you can also revert to 1.4, there is no major security update involved anyway. Just getting things ready for a transition to trino.

**Comment by keltia** [comment]
I was calculating the segments myself to feed the `hour` parameter (as specified in the Opensky documentation), I guess it is not useful anymore with 2.x?  Just specify start and end and it does everything itself?

**Comment by xoolive** [comment]
Yes, if needed it splits the query into small pieces and concats the results
